// react-toast/src/App.tsx
import { ToastContainer } from "./components/ToastContainer";
import { useToast } from "./hooks/useToast";

function App() {
  const { addToast } = useToast();

  return (
    <div>
      <h1>Toast Example</h1>
      <button
        onClick={() =>
          addToast("Hello world", { type: "success", position: "top" })
        }
      >
        Show Toast
      </button>
      <ToastContainer />
    </div>
  );
}

export default App;

// vue-toast/src/App.vue
<template>
  <div>
    <h1>Vue Toast Example</h1>
    <button @click="addToast('Hello Vue', { type: 'success', position: 'top' })">
      Show Toast
    </button>
    <ToastContainer />
  </div>
</template>

<script setup lang="ts">
import { useToast } from './composables/useToast'
import ToastContainer from './components/ToastContainer.vue'

const { addToast } = useToast()
</script>
